version: '3'
services:
  server:
      # image: build1
      build: .
      container_name: test1
      entrypoint: ""      
      command: hugo server --logLevel debug --port=8080 --bind=0.0.0.0 --watch=true --disableLiveReload=false
      working_dir: /src
      volumes:
        - ".:/src"
      ports:
        - "8080:8080"
      environment:
        PORT: 8080 
        DEBUG: 1
      # develop:
      #   watch:
      #     - action: sync
      #       path: ./data
      #       target: /src/data
      #     - action: rebuild
      #       path: ./data
      #       target: /src/data  